// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package store

type Event struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor" yaml:"actor"`

	// Data corresponds to the JSON schema field "data".
	Data EventData `json:"data" yaml:"data"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id" yaml:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind"`

	// Release corresponds to the JSON schema field "release".
	Release string `json:"release" yaml:"release"`

	// Service corresponds to the JSON schema field "service".
	Service string `json:"service" yaml:"service"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary"`

	// Ts corresponds to the JSON schema field "ts".
	Ts string `json:"ts" yaml:"ts"`
}

type EventData map[string]interface{}

type Link struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label"`

	// Link corresponds to the JSON schema field "link".
	Link string `json:"link" yaml:"link"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url"`
}

type ReleaseFrontmatter struct {
	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at" yaml:"created_at"`

	// CreatedBy corresponds to the JSON schema field "created_by".
	CreatedBy string `json:"created_by" yaml:"created_by"`

	// Image corresponds to the JSON schema field "image".
	Image string `json:"image" yaml:"image"`

	// Seq corresponds to the JSON schema field "seq".
	Seq string `json:"seq" yaml:"seq"`

	// Service corresponds to the JSON schema field "service".
	Service string `json:"service" yaml:"service"`

	// Status corresponds to the JSON schema field "status".
	Status string `json:"status" yaml:"status"`
}

type Runtime struct {
	// Command corresponds to the JSON schema field "command".
	Command string `json:"command" yaml:"command"`

	// Containers corresponds to the JSON schema field "containers".
	Containers []string `json:"containers" yaml:"containers"`

	// File corresponds to the JSON schema field "file".
	File string `json:"file" yaml:"file"`

	// Files corresponds to the JSON schema field "files".
	Files []string `json:"files" yaml:"files"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind"`

	// Names corresponds to the JSON schema field "names".
	Names []string `json:"names" yaml:"names"`

	// Project corresponds to the JSON schema field "project".
	Project string `json:"project" yaml:"project"`

	// Services corresponds to the JSON schema field "services".
	Services []string `json:"services" yaml:"services"`

	// Sockets corresponds to the JSON schema field "sockets".
	Sockets []string `json:"sockets" yaml:"sockets"`

	// Units corresponds to the JSON schema field "units".
	Units []string `json:"units" yaml:"units"`
}

type SchemaJson struct {
	// Event corresponds to the JSON schema field "event".
	Event *Event `json:"event,omitempty,omitzero" yaml:"event,omitempty"`

	// Release corresponds to the JSON schema field "release".
	Release *ReleaseFrontmatter `json:"release,omitempty,omitzero" yaml:"release,omitempty"`

	// Service corresponds to the JSON schema field "service".
	Service *ServiceFrontmatter `json:"service,omitempty,omitzero" yaml:"service,omitempty"`

	// Spec corresponds to the JSON schema field "spec".
	Spec *SpecFallback `json:"spec,omitempty,omitzero" yaml:"spec,omitempty"`
}

type ServiceFrontmatter struct {
	// Cpu corresponds to the JSON schema field "cpu".
	Cpu string `json:"cpu" yaml:"cpu"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at" yaml:"created_at"`

	// DesiredState corresponds to the JSON schema field "desired_state".
	DesiredState string `json:"desired_state" yaml:"desired_state"`

	// DisplayName corresponds to the JSON schema field "display_name".
	DisplayName string `json:"display_name" yaml:"display_name"`

	// Links corresponds to the JSON schema field "links".
	Links []Link `json:"links" yaml:"links"`

	// Memory corresponds to the JSON schema field "memory".
	Memory string `json:"memory" yaml:"memory"`

	// PackRef corresponds to the JSON schema field "pack_ref".
	PackRef string `json:"pack_ref" yaml:"pack_ref"`

	// Ports corresponds to the JSON schema field "ports".
	Ports string `json:"ports" yaml:"ports"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime *Runtime `json:"runtime,omitempty,omitzero" yaml:"runtime,omitempty"`
}

type SpecFallback struct {
	// Links corresponds to the JSON schema field "links".
	Links []Link `json:"links,omitempty,omitzero" yaml:"links,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports interface{} `json:"ports,omitempty,omitzero" yaml:"ports,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *SpecFallbackResources `json:"resources,omitempty,omitzero" yaml:"resources,omitempty"`
}

type SpecFallbackResources struct {
	// Cpu corresponds to the JSON schema field "cpu".
	Cpu string `json:"cpu" yaml:"cpu"`

	// Memory corresponds to the JSON schema field "memory".
	Memory string `json:"memory" yaml:"memory"`
}
